### ISSUE TITLE
Is Any Plugin Install in Motionbuilder?

### ISSUE THREAD

**Issue by hzhcode** [nasshu2916/MotionBuilder-Live-Sync-Unity#2]

**Comment by nasshu2916** [comment]
@hzhcode 
hi. hzhcode

This repository is Unity side library of MotionBuilder Plugin.
To use this library you need to install a plugin in MotionBuilder. The MotionBuilder plugin is published on another page, so please download it from here. (I will write an English document soon...)
https://www.naoyakohda.net/mb_sync/download

The document is only in Japanese, so please use this page as a reference.
https://www.naoyakohda.net/mb_sync/docs/ja

**Comment by hzhcode** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已经收到你邮件.
