### ISSUE TITLE
Why not support motionbuilder 2022?

### ISSUE THREAD

**Issue by DatanIMU** [nasshu2916/MotionBuilder-Live-Sync-Unity#3]

**Comment by DatanIMU** [comment]
can you compile mobu 2022? thanks

**Comment by nasshu2916** [comment]
I don't usually use MotionBuilder 2022, so I haven't compiled and checked it.

If have time on my next build, i will compile and check mobu 2022.

**Comment by nasshu2916** [comment]
v0.1.1 compiled mobu 2022
https://www.naoyakohda.net/mb_sync/download/
