### ISSUE TITLE
not move in Unity

### ISSUE THREAD

**Issue by DatanIMU** [nasshu2916/MotionBuilder-Live-Sync-Unity#4]
Motionbuilder plugin start normally and unity receive package. received length and frame rate works all right.  but， the cubic in unity scene not move when lift the cubic in motionbuilder

**Comment by DatanIMU** [comment]
when I stop unity, the cubic's location is updated. 

When I click run botton， cubic not update according to mobu

**Comment by nasshu2916** [comment]
hi. @maemoKKK 

In my environment, cube also works like the video in README.md.
If the cube position is updated when Unity is stopped, I think Unity is receiving and parsing the packets correctly. 

Are MotionBuilder and Unity set to run in the background?
MotionBuilder: Always refresh viewer is enabled?
Unity: Run in background is enabled?

**Comment by nasshu2916** [comment]
Fixed a bug in v0.1.1 that serialization/deserialization of packets for sync data fails
